DROP TABLE IF EXISTS ODONTOLOGOS; CREATE TABLE ODONTOLOGOS(ID INT AUTO_INCREMENT PRIMARY KEY, NUMERO_MATRICULA INT NOT NULL, NOMBRE VARCHAR(250) NOT NULL, APELLIDO VARCHAR(250) NOT NULL);

INSERT INTO ODONTOLOGOS(NUMERO_MATRICULA, NOMBRE, APELLIDO) VALUES(20, 'Nestor', 'Real'),(21, 'Ignacio', 'Ojeda'),(22,'Luciana','Murga');